services:
    _defaults:
        autowire: true
        autoconfigure: true

    Aleksanthaar\ApisimulatorBundle\:
        resource: '../../'

    Aleksanthaar\ApisimulatorBundle\DataCollector\ApiSimulatorCollector:
        tags:
            -
                name:     'data_collector'
                template: '@Apisimulator/Collector/apisimulator.html.twig'
                id:       !php/const Aleksanthaar\ApisimulatorBundle\DataCollector\ApiSimulatorCollector::COLLECTOR_NAME

    # TODO: move everything below to compiler pass
    Aleksanthaar\ApisimulatorBundle\Extractor\RequestExtractor:
        arguments:
            $headersRemoval: '%apisimulator.headers_removal.request%'

    Aleksanthaar\ApisimulatorBundle\Extractor\ResponseExtractor:
        arguments:
            $headersRemoval: '%apisimulator.headers_removal.response%'

    Aleksanthaar\ApisimulatorBundle\Guard\CollectionGuard:
        arguments:
            $methods: '%apisimulator.guards.methods%'
            $statusCodes: '%apisimulator.guards.status_codes%'
            $paths: '%apisimulator.guards.paths%'