services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Aleksanthaar\ApisimulatorBundle\Guard\CollectionGuardInterface:
            tags: ['apisimulator.collection_guard']

    Aleksanthaar\ApisimulatorBundle\:
        resource: '../../'

    Aleksanthaar\ApisimulatorBundle\DataCollector\ApiSimulatorCollector:
        arguments:
            $guards: !tagged 'apisimulator.collection_guard'
        tags:
            -
                name:     'data_collector'
                template: '@Apisimulator/Collector/apisimulator.html.twig'
                id:       !php/const Aleksanthaar\ApisimulatorBundle\DataCollector\ApiSimulatorCollector::COLLECTOR_NAME

    # TODO: move everything below to compiler pass
    Aleksanthaar\ApisimulatorBundle\Extractor\RequestExtractor:
        arguments:
            $customWarnings:
                requestHeaders: '%apisimulator.warnings.request_headers%'
                requestBody: '%apisimulator.warnings.request_body%'
            $headersRemoval: '%apisimulator.headers_removal.request%'

    Aleksanthaar\ApisimulatorBundle\Extractor\ResponseExtractor:
        arguments:
            $headersRemoval: '%apisimulator.headers_removal.response%'

    Aleksanthaar\ApisimulatorBundle\Guard\MethodCollectionGuard:
        arguments:
            $methods: '%apisimulator.guards.methods%'

    Aleksanthaar\ApisimulatorBundle\Guard\StatusCodeCollectionGuard:
        arguments:
            $statusCodes: '%apisimulator.guards.status_codes%'

    Aleksanthaar\ApisimulatorBundle\Guard\PathCollectionGuard:
        arguments:
            $paths: '%apisimulator.guards.paths%'